services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_USER: tamal
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/data/postgres